### ISSUE TITLE
Update Loop Because Wrong Version Number in DLL

### ISSUE THREAD

**Issue by spec1re** [jellyfin/jellyfin-plugin-playbackreporting#14]
The DDL in jellyfin-plugin-playbackreporting_**5**.0.0.0.zip has the old version number of **4**.0.0.0, so the update is failing all the time.

![image](https://user-images.githubusercontent.com/11883076/80821991-0fa7ad80-8bda-11ea-9f14-27fc2ab1639d.png)

**Comment by TheNamelessWonderer** [comment]
Same issue here. It keeps updating it every 24 hours.

**Comment by bbalz** [comment]
Same.

**Comment by spec1re** [comment]
Thanks.
