### ISSUE TITLE
[Security Issue] Registered routes publicly available

### ISSUE THREAD

**Issue by GigaFyde** [jellyfin/jellyfin-plugin-playbackreporting#23]
As of right now, all routes registed by the plugin don't seem to be secured in any way.
This means anyone could access and read the data.

Example route: http://localhost:8096/emby/user_usage_stats/user_activity
It's not limited to localhost only.

Would like to see this limited to authorized admin users only.

![image](https://user-images.githubusercontent.com/8044811/91638921-30123800-ea13-11ea-9a25-a4c658b4bacb.png)

**Comment by oddstr13** [comment]
This should be fixed now

**Comment by GigaFyde** [comment]
Happy to report that it's indeed no longer publicly accessible from the looks of it.
Greatly appreciated.
