### ISSUE TITLE
Time column in User Playback Report displays time in UTC

### ISSUE THREAD

**Issue by jfranki** [jellyfin/jellyfin-plugin-playbackreporting#24]
This **Time** column should display time in the timezone of the server (e.g. activity events in the dashboard show the correct time).

_Jellyfin 10.6.2
Linux x64 (Docker)
Playback Reporting 7.0.0.0_

**Comment by oddstr13** [comment]
Server time is never relevant for user display, it should either be UTC, or more preferably browser (user) time.
