### ISSUE TITLE
Plugin dashboard page broken on 10.7

### ISSUE THREAD

**Issue by TheNamelessWonderer** [jellyfin/jellyfin-plugin-playbackreporting#29]
I have compiled the plugin for 10.7 but when trying to access the settings page it doesn't load correctly. Instead I get this: 
![image](https://user-images.githubusercontent.com/56267607/101262372-1da44a80-3736-11eb-921b-c4337e8ca221.png)
It seems to overlay it onto the previous page you were on.

**Comment by mahriman** [comment]
Same. Console output:
```
Uncaught (in promise) Error: Failed to import: https://jellyfinhost/web/#!/configurationpage?name=user_playback_report.js
    at HTMLScriptElement.a.onerror (main.bundle.js:2)

a.onerror | @ | main.bundle.js:2
-- | -- | --
  | Promise.then (async) |   |  
  | value | @ | main.bundle.js:2
  | value | @ | main.bundle.js:2
  | (anonymous) | @ | main.bundle.js:2


```

**Comment by TheNamelessWonderer** [comment]
This wasn’t fixed in RC2

**Comment by dmitrylyzo** [comment]
> This wasn’t fixed in RC2.

Playback Reporting 9.0.0.0 works fine, but my server is `unstable` and web is `release-10.7.z`.
Is any error in browser console?

**Comment by TheNamelessWonderer** [comment]
It's a CSP issue. I'm using Nginx with the reverse proxy configuration from the docs. In the console I'm getting `Content Security Policy: The page’s settings blocked the loading of a resource at blob:https://server.org/d1daa0a9-0a07-4172-b60e-a07ae708fb31 (“script-src”) and then Uncaught (in promise)` and `Error: Failed to import: https://server.org/web/configurationpage?name=user_report.js`

Disabling CSP resolves the issue.

**Comment by TheNamelessWonderer** [comment]
Adding blob: to script-src fixes it. I'll submit an update to the docs. Sorry about that!

**Comment by Artiume** [comment]
can you make a pr to the docs?

**Comment by TheNamelessWonderer** [comment]
Will do!
