### ISSUE TITLE
Something wrong with playback count & play reporting 

### ISSUE THREAD

**Issue by alashow** [jellyfin/jellyfin-plugin-playbackreporting#32]
It's showing very high numbers for some reason as shown in screenshots below. I can provide a backup file for debugging if needed.
<img width="1043" alt="Screen Shot 2021-01-17 at 2 16 02 PM" src="https://user-images.githubusercontent.com/5840013/104855277-6c1a3c80-58d1-11eb-83e0-062eb4f4b5d7.png">
<img width="1052" alt="Screen Shot 2021-01-17 at 2 16 31 PM" src="https://user-images.githubusercontent.com/5840013/104855282-6f152d00-58d1-11eb-920f-e26ab78d4db0.png">

<img width="1319" alt="Screen Shot 2021-01-17 at 2 41 27 PM" src="https://user-images.githubusercontent.com/5840013/104855439-6c670780-58d2-11eb-988a-c5d05e4ee4cf.png">

**Comment by MrCrowley2** [comment]
can confirm something broke with 10.7.
I don't have the high play count, but the detail view for the users when I select one from the graph is always empty.

**Comment by danieladov** [comment]
I do also have both problems

**Comment by DougS2K** [comment]
Same issue here since updating to JF 10.7. [Wrong play count and no history below](https://drive.google.com/file/d/1kY_lPJ3hNk_-iDS14MoyFRiKSob1SU75/view?usp=sharing)

**Comment by whalehub** [comment]
@oddstr13 Any chance we could get a new release with this fix?

**Comment by MrCrowley2** [comment]
yeah a release would be nice. I built it myself and can confirm it to be working great with 10.7.1
