### ISSUE TITLE
Can't set backup path (JF 10.7.1, Plugin version 9.0.0.0)

### ISSUE THREAD

**Issue by Extarys** [jellyfin/jellyfin-plugin-playbackreporting#38]
Under **Settings > Backup**, clicking `Set Backup Path` does nothing, therefore backup is impossible.
![image](https://user-images.githubusercontent.com/11581433/112562574-eec9e700-8dad-11eb-8321-cb3219334de2.png)

I'm not sure if maybe a configuration option in my setup is the cause or if this is indeed a bug from this plugin.
I noticed this as I wanted to back this up and make a fresh JF installation.

**Comment by redactedscribe** [comment]
`Uncaught ReferenceError: require is not defined`, file: .../web/configurationpage?name=playback_report_settings.js:200

Firefox 87.0

**Comment by Arcanum417** [comment]
Experiencing the same bug, version 10

**Comment by xBelladonna** [comment]
Same error here, using version 10 on Firefox 87 (Linux)
```
Uncaught ReferenceError: require is not defined
    setBackupPathPicker https://redact.ed/web/configurationpage?name=playback_report_settings.js:200
```

**Comment by alexason** [comment]
Same error here - Version: 10.7.2, Firefox 88, Linux

**Comment by kimpig** [comment]
Same error - JF 10.7.6 on Chrome

**Comment by Extarys** [comment]
Please stop commenting "Same error" as the plugin is currently broken with the Jellyfin version 10.7. :smile: 

Simply upvote the top comment to let other people know you are interested in having a fix.

**Comment by Ember-ruby** [comment]
It'd be great for this to be fixed, this plugin is really quite helpful and it'd be a shame for the years of playback history to be gone, with no way to restore.

**Comment by SirMaple** [comment]
I was able to edit `playback_reporting.xml` and manually edit/set the path.

`/etc/jellyfin/playback_reporting.xml`

```<?xml version="1.0" encoding="utf-8"?>
<ReportPlaybackOptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <MaxDataAge>-1</MaxDataAge>
  <BackupPath>/mnt/volume0/jellyfin/playback_reporting_backup/</BackupPath>
  <MaxBackupFiles>5</MaxBackupFiles>
</ReportPlaybackOptions>
````
I then restarted Jellyfin and was able to complete a Playback Reporting backup.

I'm running Jellyfin on Debian Bullseye installed from the Jellyfin repository.
