### ISSUE TITLE
[Issue]: User playback report not working. 

### ISSUE THREAD

**Issue by ananthanandanan** [jellyfin/jellyfin-plugin-playbackreporting#51]
### Please describe your bug

User playback not working.
{timezoneOffset: ["The value '5.5' is not valid."]}

### Jellyfin Version

10.7.7

### Environment

```markdown
- OS:Ubuntu
- Virtualization: Docker
- Browser: Chrome
```

### Please attach any browser or client logs here

errors: {timezoneOffset: ["The value '5.5' is not valid."]}
timezoneOffset: ["The value '5.5' is not valid."]
0: "The value '5.5' is not valid."
status: 400
title: "One or more validation errors occurred."
traceId: "00-dc0f5f85f64e744c83a3e704e44d04d2-3e7269ad47648740-00"
type: "https://tools.ietf.org/html/rfc7231#section-6.5.1"

### Please attach any screenshots here

![2021-12-13_00-38](https://user-images.githubusercontent.com/53400471/145726101-8bfefea5-775b-4ef2-9c09-bc2ab8deb065.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Mountaineer1024** [comment]
Just jumping in to confirm this.

Jellyfin Version
10.7.7

Environment
- OS:Ubuntu
- Virtualization: Docker
- Browser: Chrome/Firefox (screenshots are from chrome)

Data is definitely being stored, if I set my computers timezone to a whole number such as UTC it works:

![Playback Reporting UTC](https://user-images.githubusercontent.com/3783142/151744336-18c43cbd-ee6d-4bec-a653-0bca734d9920.png)

But fails if I set it to a half hour offset such as +5:30:

![Playback Reporting +5 30](https://user-images.githubusercontent.com/3783142/151744407-cef21c12-033b-44a9-884c-8fdfe0b54d3a.png)
