### ISSUE TITLE
After docker upgrade to last version is Playback Reporting11.0.0.0 Status: NotSupported

### ISSUE THREAD

**Issue by Termalator** [jellyfin/jellyfin-plugin-playbackreporting#53]
I upgraded my docker image from jellyfin/jellyfin:unstable and after that the Playback Reporting plugin seems to be not supported, is there a workaround for that issue?

**Comment by crobibero** [comment]
Thank you for notifying us. There are a few plugins that need to be updated due to some changes in the server code.

Workaround is to use a tag from before the change was merged (https://github.com/jellyfin/jellyfin/pull/7321)

**Comment by harsh0596** [comment]
which tag would that be?

**Comment by Termalator** [comment]
i am running currently jellyfin/jellyfin:20220212.44-unstable, this works but at some point after this tag this plugin is not supported anymore.

**Comment by Termalator** [comment]
Thank you for updating the plugin, it works now :)
