### ISSUE TITLE
Feature-Request: Save Username inside the playback_reporting.db in addition to UserID

### ISSUE THREAD

**Issue by iluvatyr** [jellyfin/jellyfin-plugin-playbackreporting#68]
I'm using the playback_reporting.db for a grafana dashboard and since only the ID is displayed, I cannot identify the users. Would be helpful to also have the Username in the db.

**Comment by MMMZZZZ** [comment]
You can look up the username in the `Users` table in the `jellyfin.db` file. Not sure what your exact use case is but it shouldn't be much more difficult than having it in the `playback_reporting.db`, too (which would add the need to keep the data in sync with `jellyfin.db`).

Kind regards,
Max
