### ISSUE TITLE
abnormal vision time

### ISSUE THREAD

**Issue by sebastienPoussard** [jellyfin/jellyfin-plugin-playbackreporting#74]
Hello, 
I have some abnormal vision time 

![image](https://user-images.githubusercontent.com/36790379/229872796-0e3e200a-e013-458c-b20c-e7d62205799a.png)
like 4135 minutes, i know that the few user does not reach this values, i'm wondering if that might be a bug in jellyfin or in this plugging.   
I can help and provide more data if necessary.

**Comment by sebastienPoussard** [comment]
with the query 
```
SELECT ROWID, * 
FROM PlaybackActivity 
WHERE PlayDuration > 100000
LIMIT 10
```

i've got these results 
![image](https://user-images.githubusercontent.com/36790379/229873439-c8a71b1e-5808-41ef-b7f9-6beb405d54cc.png)

**Comment by GeoffreyCoulaud** [comment]
Looks like a duplicate of issue #69

**Comment by sebastienPoussard** [comment]
yes it is.
