### ISSUE TITLE
Most dashboards are inaccessible after 10.9 update

### ISSUE THREAD

**Issue by solidsnake1298** [jellyfin/jellyfin-plugin-playbackreporting#83]
Only the initial page for the playback reporting plugin is accessible.  None of the tabs at the top center for the other views/dashboards are present.

![Screenshot from 2024-05-12 21-31-55](https://github.com/jellyfin/jellyfin-plugin-playbackreporting/assets/137357145/0280d770-c27f-452b-8e92-3c035e4808c9)

**Comment by speatzle** [comment]
I also just noticed this, for other things in the admin ui the tabs got moved to the side bar. 

I guess this was just overlooked?

The other pages are still Accessible by changing to url query from the default `/web/#/configurationpage?name=user_report` to `/web/#/configurationpage?name=breakdown_report` or any of the other pages in https://github.com/jellyfin/jellyfin-plugin-playbackreporting/tree/master/Jellyfin.Plugin.PlaybackReporting/Pages

**Comment by speatzle** [comment]
Related https://github.com/jellyfin/jellyfin-web/issues/5484

**Comment by thornbill** [comment]
Fixed in 10.9.2
